### PR TITLE
added ben_description back to sim_demo.repos

### PR DESCRIPTION
**Pull request by munzz11**
Added the ben_description reference back to sim_demo.repos and confirmed that it solves the Resource not found error when following the demo setup guide

### CODE REVIEW

**Comment by rolker** [comment]
Can you update this to point to the CCOMJHC version of the repo?

**Comment by munzz11** [comment]
> Can you update this to point to the CCOMJHC version of the repo?

Updated to correct repo!

**Comment by rolker** [comment]
Thanks!
I'm sorry to be doing this, but I just noticed another small issue. The other packages are not organized into sub-directories, but you added this entry into robots/. For consistency, can you remove the robots/ prefix?

**Review by rolker — CHANGES_REQUESTED** [review]
Line 89, remove the robots/ part.

**Review by munzz11 — COMMENTED** [review]
removed robots/

**Review by rolker — APPROVED** [review]

**Pull request merged**
