### PR TITLE
Noetic Prereq Patch

### PR DESCRIPTION
**Pull request by Marcos-Seafloor**
Creation of Noetic prereq package installation bash script and associated documentation changes

### CODE REVIEW

**Comment by rolker** [comment]
So, I dropped the install prereqs script in favor of rosdep. It reduced the number of packages still needing apt install down to 3 so I figured it was fine to not go to a script. Is rosdep not working fine for you?

**Comment by Marcos-Seafloor** [comment]
I pulled a Noetic-base docker and followed the build instructions and rosdep looked like it missed the packages I included in the prereq script so a clean build had some launch errors. If you prefer rosdep, I can trace the errors to their independent ros packages and update package.xml accordingly. I agree rosdep is the better way to go.

**Comment by rolker** [comment]
I'm adding a couple of build-depends now to cover the two system libs that I was still manually apt installing and if I can get that to work, we'll do the rosdep only way if we can get it to work on your system as well. Is that the osrf noetic docker image you are using?

**Comment by Marcos-Seafloor** [comment]
This is what I am running:
`xhost +si:localuser:root`
`docker run -it --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ros:noetic-ros-base bash`

**Comment by rolker** [comment]
Thanks for the nudges! I got CI using github actions to work and was able to find a few missing depends. Since that first workflow used a full desktop install of ROS, I setup a second workflow that uses your suggested docker image. That one helped me uncover a few more missing depend tags and project11 now seems to build fine using only rosdep to install missing dependencies.

Here's the config. Notice the step where I add a rosdep source. That's for the missing rosdep rule for which I have a PR. That should go away is the PR gets accepted.

https://github.com/CCOMJHC/project11/blob/noetic/.github/workflows/ros-base-docker.yml

rosdep PR: https://github.com/ros/rosdistro/pull/28630

PS. The jobs ran fine in my personal repo but now that I pushed them here, one failed. I'll have to investigate that later.

**Comment by Marcos-Seafloor** [comment]
Great! I'll close this pull request then. I'm looking forward to getting this in the Echoboat.

**Pull request closed without merging**
